# Generated by Django 4.2.2 on 2024-03-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='desc',
        ),
    ]
